version: '3.8'  #specifies docker compose version
services:
  web:
    ports: 
      - '1235:1235'
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*